#' Create 2 x 2 Tables from DAG based SR data
#'
#' Creates a data frame with all 2 x 2 contigency tables given a simulated data
#' set from `simulateSRS`. The tables are organized
#' as follows:
#' \tabular{lccc}{
#'    \tab event \eqn{j} \tab not event \eqn{j} \tab *total*\cr
#'   drug \eqn{i} \tab `a` \tab `c` \tab `a` + `c`\cr
#'   not drug \eqn{i} \tab `b` \tab `d` \tab `b` + `d`\cr
#'   *total* \tab `a` + `b` \tab `c` + `d` \tab `n_reports`
#' }
#'
#' @param sr The output generated by the [simulateSRS()] function
#'
#' @return A data frame where each row represents a 2 x 2 table. The columns represent:
#'   \item{`drug_id`}{The ID of the drug}
#'   \item{`event_id`}{The ID of the event}
#'   \item{`prob_drug`}{The marginal probability of that drug}
#'   \item{`prob_event`}{The marginal probability of that event}
#'   \item{`or`}{The increase of the odds ratio when the drug is on the report}
#'   \item{`associated`}{`TRUE` is there is a non-zero correlation, `FALSE` otherwise}
#'   \item{`a`}{Number of times the drug and event appeared together in a report}
#'   \item{`b`}{Number of times the event appeared without the drug in a report}
#'   \item{`c`}{Number of times the drug appeared without the event in a report}
#'   \item{`d`}{Number of times the drug and event both did not appear in a report}
#'
#' @examples
#' sr <- simulateSRS(verbose = FALSE)
#' tables <- convert2Tables(sr)
#'
#' @seealso [simulateSRS()]
#' @export
convert2Tables <- function(sr) {
  tibble::as_tibble(
    create2x2TablesDAGRcpp(
      as.matrix(sr$sr),
      sr$prob_drugs,
      sr$prob_events,
      as.integer(sr$nodes$in_degree),
      as.integer(sr$nodes$parent_id),
      sr$nodes$beta1
    )
  )
}
